// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyledGoal.DAL.Data;

#nullable disable

namespace StyledGoal.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240101205743_Add-Pie-Chart-Schema")]
    partial class AddPieChartSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StyledGoal.DAL.Models.ChartDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChartId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChartId");

                    b.ToTable("DataPoints", (string)null);
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.GeneralChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("GeneralCharts", (string)null);
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.PieChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PieCharts", (string)null);
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.PieChartDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LabelColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PieChartId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PieChartId");

                    b.ToTable("PieDataPoints", (string)null);
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.ChartDataPoint", b =>
                {
                    b.HasOne("StyledGoal.DAL.Models.GeneralChart", "Chart")
                        .WithMany("Chart")
                        .HasForeignKey("ChartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chart");
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.PieChartDataPoint", b =>
                {
                    b.HasOne("StyledGoal.DAL.Models.PieChart", "Chart")
                        .WithMany("Chart")
                        .HasForeignKey("PieChartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chart");
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.GeneralChart", b =>
                {
                    b.Navigation("Chart");
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.PieChart", b =>
                {
                    b.Navigation("Chart");
                });
#pragma warning restore 612, 618
        }
    }
}
