// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StyledGoal.DAL.Data;

#nullable disable

namespace StyledGoal.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240101192219_Add-GeneralChart-Table")]
    partial class AddGeneralChartTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StyledGoal.DAL.Models.ChartDataPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GeneralChartId")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneralChartId");

                    b.ToTable("ChartDataPoints");
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.GeneralChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("GeneralCharts", (string)null);
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.ChartDataPoint", b =>
                {
                    b.HasOne("StyledGoal.DAL.Models.GeneralChart", null)
                        .WithMany("Chart")
                        .HasForeignKey("GeneralChartId");
                });

            modelBuilder.Entity("StyledGoal.DAL.Models.GeneralChart", b =>
                {
                    b.Navigation("Chart");
                });
#pragma warning restore 612, 618
        }
    }
}
